---
layout: post
title: Go错误处理
date: '2020-11-22'
categories: [Go]
---

### Error in Go

- 错误表明程序中出现异常情况。比如尝试打开一个文件，但是该文件在文件系统中并不存在，这是一种异常情况表示为错误。

- Go中使用内置错误类型表示错误。

```go
func main(){
    f, err := os.Open("/test.txt")
    // 错误代码不为nil表示打开文件错误
    if err != nil{
        fmt.Println(err)
        return
    }
    fmt.Println(f.Name(), "opened successfully")
}
```

- Go中处理错误的惯用方式是将返回的错误与nil进行比较。nil值表示未发生错误，非nil值表示存在错误。

- `error`是一个接口

```go
type error interface{
    // 当打印错误的时候，fmt.Println函数调用该函数打印错误信息
    Error() string
}
```

- 从错误的结构体定义中提取相关的信息

```go
// 在不同错误类型中定义了相关信息
type PathError struct{
    Op      string
    Path    string
    Err     error
}

func (e *PathError) Error() string {
    return e.Op + " " + e.Path + ": " + e.Err.Error()
}
```

- 从不同错误的方法中提取相关信息

```go
type DNSError struct{
    ...
}

func (e *DNSError) Error() string{

}

// 返回该错误造成的原因是不是因为超时
func (e *DNSError) Timeout() bool{

}

// 返回该错误造成的原因是不是因为临时
func (e *DNSError) Temporary() bool{

}
```

- 错误可以进行比较

```go
func main(){
    files, err := filepath.Glob("[")
    if err != nil{
        // 对错误进行比较对比
        if err == filepath.ErrBadPattern{
            fmt.Println("Bad pattern error:", err)
            return
        }
        fmt.Println("Generic error:", err)
        return
    }
    fmt.Println("matched files", files)
}
```

- 不要忽略错误，否则会导致更大的问题



### 创建自定义错误类型

- 使用`New()`函数创建新错误类型

```go
// Package errors implements functions to manipulate errors.
package errors
// New returns an error that formats as the given text.
func New(text string) error {
    return &errorString{text}
}

// errorString is a trivial implementation of error.
type errorString struct {
    s string
}

func (e *errorString) Error() string {
    return e.s
}
```

- 使用`Errorf()`函数添加更多错误信息

```go
fmt.Errorf("Area calculation failed, radius %0.2f is less than zero", radius)
```

- 使用结构体类型和字段提供有关错误的更多信息

```go
type areaError struct{
    err     string
    radius  float64
}

func (e *areaError) Error() string{
    return fmt.Sprintf("radius %0.2f: %s", e.radius, e.err)
}
```

- 使用结构体类型的方法提供有关错误的更多信息

```go
type areaError struct{
    err     string
    length  float64
    width   float64
}

func (e *areaError) Error() string{
    return e.err
}

// 返回错误是否是length造成的
func (e *areaError) lengthNegative() bool{
    return e.length < 0
}

func (e *areaError) widthNegative() bool{
    return e.width < 0
}
```


### panic和recover

- 在Go程序中处理异常情况的惯用方法是使用错误，对于程序中出现的大多数异常情况，错误都可以处理

- 在某些情况下，异常情况后程序无法继续进行。在这种情况下，可以使用panic来提前终止程序。

- 当某个函数遇到紧急情况的时候，该函数会停止执行，执行完所有的defer函数，然后函数返回。

- 程序会在当前协程的所有函数返回之前继续执行，此时程序将会打印panic信息，然后stack trace，然后终止程序。


#### panic如何使用

- 首先第一原则：应该避免panic，并尽可能的使用recover和error；仅在程序无法继续执行的情况下，才使用panic和restore机制

- 遇到以下情况时使用panic：
 - 程序无法简单的继续执行的不可恢复的错误：比如绑定到所需要端口的web服务器，在这种情况下因为如果端口绑定失败，则无需执行其他任何操作。这时候应该panic
 - 程序错误：比如有一个接收指针作为参数的方法，调用者使用nil参数调用了该方法。

- recover是一个内置函数，用于重新获得对panic程序的控制

```go
func recover() interface{}
```

- 仅在内部defer函数中调用时，recover才有用。即在函数panic之前调用`defer recover()`

- 执行`recover()`函数之后，panic会停止，并且调用返回。

- `recover`之后，将失去关于panic的堆栈跟踪，有一种方法可以使用Debug包的PrintStack功能打印堆栈跟踪`debug.PrintStack()`

- `recover`只能恢复同一个协程中的panic。
